/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Kotoeri Option
 #	author : miyako
 #	2015/06/08
 #
 # --------------------------------------------------------------------------------*/



// --- Kotoeri
void Kotoeri_Get_option(sLONG_PTR *pResult, PackagePtr pParams);
void Kotoeri_SET_OPTION(sLONG_PTR *pResult, PackagePtr pParams);

#define kotoeri_app_id CFSTR("com.apple.inputmethod.Kotoeri")

#define TYPE_Is_alpha (0)
#define TYPE_Is_text (2)
#define TYPE_Is_string (24)

#define TYPE_Is_short (8)
#define TYPE_Is_int (9)
#define TYPE_Is_long (25)
#define TYPE_Is_real (1)

#define TYPE_Is_boolean (6)